//
// Created by 赵立伟 on 2018/10/13.
//

#ifndef FLYDB_FLYOBJENCODING_H
#define FLYDB_FLYOBJENCODING_H

enum FlyObjEncoding {
    FLY_ENCODING_INT,
    FLY_ENCODING_STRING,
    FLY_ENCODING_HT,
    FLY_ENCODING_LINKEDLIST,
    FLY_ENCODING_INTSET,
    FLY_ENCODING_SKIPLIST
};

#endif //FLYDB_FLYOBJENCODING_H
